# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vcloud")
    config.vm.provider :vcloud do |vcloud|
      vcloud.vapp_prefix = "vappnetwork"
      vcloud.ip_subnet = "172.16.32.0/255.255.255.0"
    end
    if Vagrant.has_plugin?("vagrant-proxyconf")
      config.vm.provider :vcloud do |cloud, override|
        override.proxy.enabled = false
      end
    end
    config.vm.provider :vcloud do |cloud, override|
      override.vm.usable_port_range = 2200..2999
    end
  end

  config.vm.define :"tst" do |tst|
    tst.vm.box = "precise32"
    tst.vm.box_url = "http://vagrant.tsugliani.fr/precise32.box"
    tst.vm.hostname = "tst"
    tst.vm.provision "shell", path: "scripts/provision.sh"
  end

end
