# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vcloud")
    config.vm.provider :vcloud do |vcloud|
      vcloud.vapp_prefix = "100mb-test"
      vcloud.ip_subnet = "192.168.33.0/255.255.255.0"
    end
    config.vm.provider :vcloud do |cloud, override|
      override.vm.usable_port_range = 2200..2999
    end
  end

  config.vm.define "server" do |config|
    config.vm.box = "ubuntu1404"
    config.vm.hostname = "server"
    config.vm.network :private_network, ip: "192.168.33.2" # VMware Fusion/VirtualBox
    config.vm.provision :shell, :path => "scripts/provision-cups.sh", :privileged => false
  end

  config.vm.define "client" do |config|
    config.vm.box = "ubuntu1404"
    config.vm.hostname = "client"
    config.vm.network :private_network, ip: "192.168.33.3" # VMware Fusion/VirtualBox
    config.vm.provision :shell, :path => "scripts/provision-client.sh", :privileged => false
  end

end
